apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-xhkp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/rsoaresd_org/spi-demos-lton-tenant/dotnet-component/devfile-sample-dotnet60-basic-xhkp@sha256:41334f2c25e70082979143569a9553fd427135b8a678088abc54e2ae78f1946b
        name: main
        resources: {}
status: {}
